cache:
  - C:\Tools\vcpkg\installed\

image:
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  CMAKE_CONFIG: MinSizeRel
  VCPKG_ROOT: C:\Tools\vcpkg

  matrix:
    - STATIC_LINK: ON
      PLATFORM: x64-windows-static
    - STATIC_LINK: OFF
      PLATFORM: x64-windows

install:
  - ps: (git -C "$env:VCPKG_ROOT" pull origin master) -Or ($True)
  - ps: bootstrap-vcpkg.bat
  # Return code will be false when installing boost-system, even it's installed correctly.
  - ps: (vcpkg install boost-system:"$env:PLATFORM") -Or ($True)
  - ps: |
      vcpkg install boost-asio:"$env:PLATFORM" boost-beast:"$env:PLATFORM" `
        boost-coroutine2:"$env:PLATFORM" boost-filesystem:"$env:PLATFORM" `
        boost-mpl:"$env:PLATFORM" boost-program-options:"$env:PLATFORM" `
        boost-test:"$env:PLATFORM" libmaxminddb:"$env:PLATFORM" `
        libsodium:"$env:PLATFORM" mbedtls:"$env:PLATFORM" rapidjson:"$env:PLATFORM"

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017

    before_build:
      - ps: |
          cmake -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET="$env:PLATFORM" -DCMAKE_BUILD_TYPE="$env:CMAKE_CONFIG" `
            -DSTATIC_LINK="$env:STATIC_LINK" -G "Visual Studio 15 2017 Win64" .

  -
    matrix:
      only:
        - image: Visual Studio 2019

    before_build:
      - ps: |
          cmake -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET="$env:PLATFORM" -DCMAKE_BUILD_TYPE="$env:CMAKE_CONFIG" `
            -DSTATIC_LINK="$env:STATIC_LINK" -A x64 -G "Visual Studio 16 2019" .
       
build_script:
  - ps: $cs = Get-WmiObject -class Win32_ComputerSystem
  - ps: $Cores = $cs.numberoflogicalprocessors
  - ps: cmake --build . --config "$env:CMAKE_CONFIG" -j "$Cores"

test_script:
  - ps: $env:PATH = "$env:PATH;$env:VCPKG_ROOT\installed\$env:PLATFORM\bin"
  - ps: $env:PATH = "$env:PATH;$(pwd)\src\$env:CMAKE_CONFIG"
  - ps: ctest --output-on-failure -C "$env:CMAKE_CONFIG"
