cache:
  - C:\Tools\vcpkg\installed\

image:
  - Visual Studio 2017

environment:
  PLATFORM: x64-windows
  CMAKE_GEN: "Visual Studio 15 2017 Win64"
  CMAKE_CONFIG: MinSizeRel
  VCPKG_ROOT: C:\Tools\vcpkg

  matrix:
    - STATIC_LINK: ON
    - STATIC_LINK: OFF

install:
  - ps: |
      vcpkg install boost-asio:x64-windows boost-beast:x64-windows boost-coroutine2:x64-windows `
        boost-filesystem:x64-windows boost-mpl:x64-windows boost-program-options:x64-windows `
        boost-test:x64-windows libmaxminddb:x64-windows libsodium:x64-windows mbedtls:x64-windows `
        rapidjson:x64-windows

for:
-
  before_build:
    - ps: |
        cmake -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
          -DVCPKG_TARGET_TRIPLET="$env:PLATFORM" -DSTATIC_LINK="$env:STATIC_LINK" `
          -G "$env:CMAKE_GEN" .

  build_script:
    - ps: $cs = Get-WmiObject -class Win32_ComputerSystem
    - ps: $Cores = $cs.numberoflogicalprocessors
    - ps: cmake --build . --config "$env:CMAKE_CONFIG" -j "$Cores"

  test_script:
    - ps: $env:PATH = "$env:PATH;$env:VCPKG_ROOT\installed\$env:PLATFORM\bin"
    - ps: $env:PATH = "$env:PATH;$(pwd)\src\$env:CMAKE_CONFIG"
    - ps: ctest --output-on-failure -C "$env:CMAKE_CONFIG"
