cache:
  - C:\Tools\vcpkg\installed\

image:
  - Visual Studio 2017

environment:
  matrix:
    - PLATFORM: x64-windows
      CMAKE_GEN: "Visual Studio 15 2017 Win64"

install:
  - ps: |
      vcpkg install boost-asio:x64-windows boost-beast:x64-windows boost-coroutine2:x64-windows `
        boost-mpl:x64-windows boost-program-options:x64-windows boost-test:x64-windows `
        libmaxminddb:x64-windows libsodium:x64-windows mbedtls:x64-windows rapidjson:x64-windows

for:
-
  build_script:
    - ps: |
        cmake -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET="$env:PLATFORM" -G "$env:CMAKE_GEN" .
    - ps: cmake --build . --config Debug
    - ps: cmake --build . --config Release

  test_script:
    - ps: ctest --output-on-failure -C Debug
    - ps: ctest --output-on-failure -C Release
