language: cpp
sudo: false

matrix:
  include:
    - os: linux
      services:
        - docker
      env:
        - PLATFORM=alpine
        - BUILD_TYPE="Debug"
        - PARALLEL="$(nproc)"
    - os: linux
      services:
        - docker
      env:
        - PLATFORM=alpine
        - BUILD_TYPE="Release"
        - PARALLEL="$(nproc)"
    - os: osx
      addons:
        homebrew:
          packages:
            - cmake
            - llvm
            - boost
            - mbedtls
            - libsodium
            - libmaxminddb
            - rapidjson
      env:
        - PLATFORM=osx
        - BUILD_TYPE="Debug"
        - PARALLEL="$(sysctl -n hw.physicalcpu)"
    - os: osx
      addons:
        homebrew:
          packages:
            - cmake
            - llvm
            - boost
            - mbedtls
            - libsodium
            - libmaxminddb
            - rapidjson
      env:
        - PLATFORM=osx
        - BUILD_TYPE="Release"
        - PARALLEL="$(sysctl -n hw.physicalcpu)"

install:
  - |
    if [[ "${PLATFORM}" = "alpine" ]]; then
      docker build --rm --no-cache -t pichi/builder -f docker/builder.dockerfile .
    fi

script:
  - mkdir -p build
  - cd build
  - |
    case "${PLATFORM}" in
      "alpine")
        docker run --rm -v "${TRAVIS_BUILD_DIR}:/root/pichi" -w /root/pichi/build \
          pichi/builder cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" /root/pichi &&
        docker run --rm -v "${TRAVIS_BUILD_DIR}:/root/pichi" -w /root/pichi/build \
          pichi/builder make -j "${PARALLEL}" &&
        docker run --rm -v "${TRAVIS_BUILD_DIR}:/root/pichi" -w /root/pichi/build \
          pichi/builder ctest --output-on-failure;;
      "osx")
        cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
          -DCMAKE_CXX_COMPILER="$(brew --prefix)/opt/llvm/bin/clang++" \
          "${TRAVIS_BUILD_DIR}" &&
        make -j "${PARALLEL}" &&
        ctest --output-on-failure;;
    esac

notifications:
  email: false
