parameters:
  buildTarget: "all"
  testTarget: "test"
  generator: 'Unix Makefiles'
  extraArgs: ''

steps:
  - bash: >
      echo "##vso[task.setvariable variable=PARALLEL]$(sysctl -n hw.physicalcpu)"
    displayName: "Get the number of cores"
    condition: eq(variables['Agent.OS'], 'Darwin')
  - bash: >
      echo "##vso[task.setvariable variable=PARALLEL]$(nproc)"
    displayName: "Get the number of cores"
    condition: eq(variables['Agent.OS'], 'Linux')
  - powershell: >
      $cs = Get-WmiObject -class Win32_ComputerSystem;
      $Cores = $cs.numberoflogicalprocessors;
      echo "##vso[task.setvariable variable=PARALLEL]$Cores"
    displayName: "Get the number of cores"
    condition: eq(variables['Agent.OS'], 'Windows_NT')
  - powershell: >
      $env:PATH += ";$(VCPKG_INSTALLATION_ROOT)\installed\$(PLATFORM)\bin";
      $env:PATH += ";$(Build.BinariesDirectory)\src\$(CMAKE_CONFIG)";
      echo "##vso[task.setvariable variable=PATH]$env:PATH"
    displayName: "Setup PATH"
    condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['STATIC_LINK'], 'OFF'))
  - template: ./cmake.yml
    parameters:
      name: Pichi
      buildTarget: ${{ parameters.buildTarget }}
      testTarget: ${{ parameters.testTarget }}
      generator: ${{ parameters.generator }}
      arguments: -D CMAKE_BUILD_TYPE=$(CMAKE_CONFIG) -D STATIC_LINK=$(STATIC_LINK) -D ENABLE_TLS=ON -D BUILD_TEST=ON -D BUILD_SERVER=ON ${{ parameters.extraArgs }}
      config: $(CMAKE_CONFIG)
      cwd: $(Build.BinariesDirectory)
      src: $(Build.SourcesDirectory)
