parameters:
  name: ''
  displayName: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        static_debug:
          STATIC_LINK: "ON"
          CMAKE_CONFIG: "Debug"
        static_release:
          STATIC_LINK: "ON"
          CMAKE_CONFIG: "MinSizeRel"
        dynamic_debug:
          STATIC_LINK: "OFF"
          CMAKE_CONFIG: "Debug"
        dynamic_release:
          STATIC_LINK: "OFF"
          CMAKE_CONFIG: "MinSizeRel"
    steps:
      - bash: >
          echo "##vso[task.setvariable variable=PARALLEL]$(sysctl -n hw.physicalcpu)"
        displayName: "Get the number of cores"
      - script: brew install boost mbedtls libsodium libmaxminddb libressl rapidjson
        displayName: "Prepare dependent packages"
      - task: CMake@1
        displayName: "Generate building files"
        inputs:
          cmakeArgs: >
            -DOPENSSL_ROOT_DIR=/usr/local/opt/libressl
            -DCMAKE_BUILD_TYPE=$(CMAKE_CONFIG)
            -DSTATIC_LINK="$(STATIC_LINK)"
            -DENABLE_TLS=ON
            -B "$(Build.SourcesDirectory)/build"
            $(Build.SourcesDirectory)
      - task: CMake@1
        displayName: "Build all"
        inputs:
          cmakeArgs: >
            --build "$(Build.SourcesDirectory)/build"
            -j $(PARALLEL)
            --target all
      - task: CMake@1
        displayName: "Run unit tests"
        inputs:
          cmakeArgs: >
            --build "$(Build.SourcesDirectory)/build"
            --target test
