jobs:
  - job: alpine
    displayName: Alpine in Docker
    pool:
      vmImage: ubuntu-18.04
    variables:
      - name: DOCKER_IMAGE
        value: pichi/builder
      - name: SRC_DIR
        value: /root/pichi
      - name: BIN_DIR
        value: /tmp/pichi
    strategy:
      matrix:
        static_debug:
          STATIC_LINK: "ON"
          CMAKE_CONFIG: "Debug"
        static_release:
          STATIC_LINK: "ON"
          CMAKE_CONFIG: "MinSizeRel"
        dynamic_debug:
          STATIC_LINK: "OFF"
          CMAKE_CONFIG: "Debug"
        dynamic_release:
          STATIC_LINK: "OFF"
          CMAKE_CONFIG: "MinSizeRel"
    steps:
      - bash: echo "##vso[task.setvariable variable=PARALLEL]$(nproc)"
        displayName: "Get the number of cores"
      - task: Docker@2
        displayName: "Prepare docker image"
        inputs:
          command: build
          Dockerfile: $(Build.SourcesDirectory)/docker/builder.dockerfile
          buildContext: $(Build.SourcesDirectory)
          arguments: -t $(DOCKER_IMAGE)
      - task: Docker@2
        displayName: "Generate building files"
        inputs:
          command: run
          arguments: >
            -v $(Build.BinariesDirectory):$(BIN_DIR)
            -v $(Build.SourcesDirectory):$(SRC_DIR):ro
            $(DOCKER_IMAGE)
            cmake -DCMAKE_BUILD_TYPE=$(CMAKE_CONFIG)
            -DSTATIC_LINK=$(STATIC_LINK)
            -B $(BIN_DIR)
            $(SRC_DIR)
      - task: Docker@2
        displayName: "Build all"
        inputs:
          command: run
          arguments: >
            -v $(Build.BinariesDirectory):$(BIN_DIR)
            -v $(Build.SourcesDirectory):$(SRC_DIR):ro
            $(DOCKER_IMAGE)
            cmake --build $(BIN_DIR) -j $(PARALLEL) --target all
      - task: Docker@2
        displayName: "Run unit tests"
        inputs:
          command: run
          arguments: >
            -v $(Build.BinariesDirectory):$(BIN_DIR)
            $(DOCKER_IMAGE)
            cmake --build $(BIN_DIR) --target test
