jobs:
  - job: android
    displayName: Android
    pool:
      vmImage: ubuntu-22.04
    strategy:
      matrix:
        armv8:
          args: "-a armv8 -l 33 -p android"
        armv7:
          args: "-a armv7 -l 33 -p android"
        armv7hf:
          args: "-a armv7hf -l 33 -p android"
    steps:
      - bash: >
          sudo apt install -y cmake git patch python3-pip
        displayName: Install the necessary packages
      - bash: >
          sudo pip install conan
        displayName: Inatall Conan
      - template: ./conan.yml
        parameters:
          buildArgs: $(args) -r ${ANDROID_NDK_HOME} -d
