jobs:
  - job: ios
    displayName: iOS
    pool:
      vmImage: macos-12
    strategy:
      matrix:
        armv8_release:
          args: "-a armv8 -p ios"
        armv8_debug:
          args: "-d -a armv8 -p ios"
        armv8.3_release:
          args: "-a armv8.3 -p ios"
        armv8.3_debug:
          args: "-d -a armv8.3 -p ios"
        x86_64_release:
          args: "-a x86_64 -p ios"
        x86_64_debug:
          args: "-d -a x86_64 -p ios"
    steps:
      - bash: >
          brew install cmake conan
        displayName: Install the necessary packages
      - template: ./conan.yml
        parameters:
          buildArgs: $(args) -v 15.0
