jobs:
  - job: macos
    displayName: macOS 12
    pool:
      vmImage: macos-12
    strategy:
      matrix:
        static_debug:
          args: "-d"
        static_release:
          args: ""
        dynamic_debug:
          args: "-ds"
        dynamic_release:
          args: "-s"
    steps:
      - bash: >
          brew install cmake conan
        displayName: Install the necessary packages
      - template: ./conan.yml
        parameters:
          buildArgs: $(args) -p macos
