jobs:
  - job: windows
    displayName: Windows 2022
    pool:
      vmImage: windows-2022
    strategy:
      matrix:
        static_debug:
          args: "-dp windows"
        static_release:
          args: "-p windows"
        dynamic_debug:
          args: "-dsp windows"
        dynamic_release:
          args: "-sp windows"
    steps:
      - powershell: >
          choco install -y conan nasm
        displayName: Install conan
      - template: ./conan.yml
        parameters:
          buildArgs: $(args) -p windows
