jobs:
  - job: windows
    displayName: Windows 2022
    pool:
      vmImage: windows-2022
    strategy:
      matrix:
        debug:
          args: "-dp windows"
        release:
          args: "-p windows"
    steps:
      - powershell: >
          choco install -y conan
        displayName: Install conan
      - template: ./conan.yml
        parameters:
          buildArgs: $(args) -p windows
